### ISSUE TITLE
Edit on github link points to meteor/guide

### ISSUE THREAD

**Issue by zol** [apollostack/docs#123] opened 2016-06-28 05:48 UTC
The "Edit this page on GitHub" link at the bottom of the docs pages points to the wrong spot.

**Comment by stubailo** [comment] 2016-06-28 06:08
Duplicate of #97

**Closed by stubailo** 2016-06-28 06:08 UTC

**Comment by zol** [comment] 2016-06-28 06:51
Sorry, must have scrolled past this when looking at the existing issues.
